name: Deploy to WordPress.org SVN
on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Plugin-Slug
        run: |
            echo "PLUGIN=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    - name: Checkout-Code
      uses: actions/checkout@v7
    - name: WordPress-Plugin-Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SLUG: ${{ env.PLUGIN }}
        ASSETS_DIR: .wp-assets
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

    # After the deploy, we also want to create a zip and upload it to the release on Github. We don't want
    # users to have to go to the repository to find our plugin :).
    - name: Upload-Release-Asset
      uses: softprops/action-gh-release@v3
      env:
        # Note, this is an exception to action secrets: GH_TOKEN is always available and provides access to
        # the current repository this action runs in.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Provide what the file should be named when attached to the release (plugin-name.zip)
        files: ${{ github.workspace }}/${{ env.PLUGIN }}.zip
        # ${{ github.event.repository.name }}.zip
